site_name: Debezium Server Iceberg Consumer
site_url: https://memiiso.github.io/debezium-server-iceberg
repo_url: https://github.com/memiiso/debezium-server-iceberg
theme:
  name: material
  features:
    #    - navigation.instant
    - navigation.indexes
    - navigation.tabs
    #    - navigation.expand
    - toc.integrate
    - toc.follow
    - navigation.path
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
nav:
  - Home: index.md
  - Iceberg Consumer: iceberg.md
  - IcebergEvents Consumer: icebergevents.md
  - Python Runner: python-runner.md
  - Migration Guideline: migration.md
  - FAQ: faq.md
  - Contributing: contributing.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: [ !relative $config_dir ]
      check_paths: true
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - abbr
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/memiiso/debezium-server-iceberg