name: Create Release of master branch

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set env
        run: |
          echo "RELEASE_NAME=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          echo "RELEASE_BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
          echo "RELEASE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build project
        run: mvn -B package -Passembly --file pom.xml -Drevision=latest

      - name: Delete latest release
        uses: dev-drprasad/delete-tag-and-release@v0.1.3
        with:
          delete_release: true # default: false
          tag_name: latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: latest
          tag_name: latest
          body: release of master branch
          draft: false
          prerelease: false
          files: debezium-server-dist/target/debezium-server-dist-latest.zip