name: CI to Github Container Registry

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Main
    if: github.repository_owner == 'memiiso'
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v2
        name: Build & push Docker image
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/debezium-server-iceberg:latest