name: CI to Github Container Registry

on:
  push:
    branches: [ cr ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Set env
        run: |
          echo "RELEASE_NAME=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          echo "RELEASE_BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
          echo "RELEASE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          
      - name: Build project
        run: mvn -B --quiet package -Passembly --file pom.xml -Drevision=latest

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/debezium-server-iceberg:latest
          
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}