name: "Close Stale Issues and PRs"
on:
  schedule:
    - cron: '0 0 * * *'

permissions:
  # All other permissions are set to none
  issues: write
  pull-requests: write

jobs:
  stale:
    if: github.repository_owner == 'memiiso'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/stale@v9.1.0
        with:
          # stale issues
          stale-issue-label: 'stale'
          exempt-issue-labels: 'not-stale'
          days-before-issue-stale: 180
          days-before-issue-close: 14
          stale-issue-message: >
            This issue has been automatically marked as stale because it has been open for 180 days
            with no activity. It will be closed in next 14 days if no further activity occurs. To
            permanently prevent this issue from being considered stale, add the label 'not-stale',
            but commenting on the issue is preferred when possible.
          close-issue-message: >
            This issue has been closed because it has not received any activity in the last 14 days
            since being marked as 'stale'
          # stale PRs
          stale-pr-label: 'stale'
          exempt-pr-labels: 'not-stale,security'
          stale-pr-message: 'This pull request has been marked as stale due to 30 days of inactivity. It will be closed in 1 week if no further activity occurs. If you think that’s incorrect or this pull request requires a review, please simply write any comment. If closed, you can revive the PR at any time. Thank you for your contributions.'
          close-pr-message: 'This pull request has been closed due to lack of activity. This is not a judgement on the merit of the PR in any way. It is just a way of keeping the PR queue manageable. If you think that is incorrect, or the pull request requires review, you can revive the PR at any time.'
          days-before-pr-stale: 30
          days-before-pr-close: 7
          ascending: true
          operations-per-run: 200
